spring:
  application:
    name: ATF
  main:
    banner-mode: off
    log-startup-info: false
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false

server:
  servlet:
    context-path: /atf
  tomcat:
    max-threads: ${TOMCAT_MAX_THREADS:200}
    min-spare-threads: ${TOMCAT_MIN_THREADS:20}
  shutdown: graceful
  port: ${PORT:5000}

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml

logging:
  level:
    root: ${LOG_LEVEL:INFO}

request:
  http-headers:
    api-key: ${API-KEY:atf}
